Update asset ownership as mandatory field
GRESB/api-docs pull request #131
Opened 2023-02-20 14:55 UTC by GokceBaykan

Also removes user endpoint and moves certification & energy ratings notices.

2023-02-21 15:04 UTC, joeyhorst requested changes
We missed a section for clarifying `asset_ownership` as mandatory field. The user of notices seems slightly off to me. Lastly made some comments on existing text - I know I wrote most of it a while back, but looking at it with fresh eyes.

2023-02-23 13:46 UTC, GokceBaykan commented on source/includes/_assets.md
> +The `year` in _annual_data_ is required along with `asset_size`,`property_type_code`, `asset_name` and `asset_ownership`.
I rechecked and you are right: [country, state_province, city] are mandatory fields. Changed the text to clarify on all the mandatory fields and if they need to be posted per annual data or year agnostically.

2023-02-23 14:06 UTC, GokceBaykan commented on source/includes/_assets.md
> +The `year` in _annual_data_ is required along with `asset_size`,`property_type_code`, `asset_name` and `asset_ownership`.
It seems asset_ownership is not a mandatory field for always_create. [Asset](https://portal.dev.gresb.com/asset_portal/r/entities/21621-no-import/assets/901358/edit?validation_context=main) without this field will still be created.

![Screenshot 2023-02-23 at 15 05 11](https://user-images.githubusercontent.com/100768664/220930287-8d98734e-16a4-44f3-b6e1-19de4b94bcb2.png)

2023-02-24 10:13 UTC, GokceBaykan commented
Updated the branch, it is ready for review again. @joeyhorst

2023-03-03 12:46 UTC, joeyhorst approved these changes
looks good 👍 thanks for making the style changes

2023-03-03 12:51 UTC, merged