Introduction of year as mandatory field for certifications
GRESB/api-docs pull request #162
Opened 2024-02-05 13:11 UTC by GokceBaykan

This PR addressed the introduction of `Year` as mandatory field for Building Certifications

2024-02-06 13:07 UTC, joeyhorst requested changes
Mostly remove some trailing commas in the examples and add `year` to the data dictionary.

2024-02-06 14:49 UTC, GokceBaykan commented on source/includes/_assets.md
> +  - energy ratings
This explains. I tried to retract the change in the other branch but couldn't see and thought I imagined it 🤣

2024-02-06 14:57 UTC, GokceBaykan commented on source/includes/_assets.md
> +            "year": 2017,
This view cuts the visibility of the code in a misleading way. In each of the instances we actually have `_validations` following the `year` as part of the the array.

<img width="421" alt="Screenshot 2024-02-06 at 15 56 33" src="https://github.com/GRESB/api-docs/assets/100768664/edf157dd-9086-4df1-b8da-43d64b05db0b">

2024-02-06 15:23 UTC, GokceBaykan commented on source/includes/_certifications.md
> +`{ "certifications": [{ "certification_id": 598, "level": "GoldPlus", "size": 123, "year": 2017 }] }`
I realised this is actually duplication since we already have it as JSON on the side as well 😆 removed it

2024-02-22 13:51 UTC, joeyhorst commented on source/includes/_assets.md
> +            "year": 2017,
you're right, good catch!

2024-02-22 13:52 UTC, joeyhorst approved these changes
looks good to me - let's wait till the API changes are on prod before merging this since it will automatically publish the docs on the internet

2024-02-29 15:50 UTC, merged