Made Changes in Request and Response Body of https://github.com/GRESB/api-docs/blob/master/source/includes/_assets.md
GRESB/api-docs pull request #89
Opened 2022-02-25 04:41 UTC by naincygoyal

I have made these changes https://github.com/GRESB/api-docs/issues/88#issuecomment-1049779332 in https://github.com/GRESB/api-docs/blob/master/source/includes/_assets.md

2022-02-25 07:23 UTC, joeyhorst requested changes
Main comments are around location and the example used. Probably better to make a smaller example.

2022-02-25 07:23 UTC, joeyhorst commented on source/includes/_assets.md
> +    "country": "CD",
please change it to `NL` to be consistent with a "real"(ish) location

Using the GRESB Office as location and name could be nice.

2022-02-25 07:23 UTC, joeyhorst commented on source/includes/_assets.md
> +    "address": "ABC",
rather use a real address or none at all - this gives a bad example

2022-02-25 07:23 UTC, joeyhorst commented on source/includes/_assets.md
> +    "annual_data": [
either create a minimum viable asset or fill in all the fields (including `asset_ownership`, `construction_year` etc.

The current example has a lot of yearly data, but is missing some of the asset characteristics. I would suggest to lower the number of annual_data fields.

2022-02-25 07:23 UTC, joeyhorst commented on source/includes/_assets.md
> +    "gresb_asset_id": 833335,
This response will change according to the changes made above.

2022-02-25 07:23 UTC, joeyhorst commented on source/includes/_assets.md
> +            "asset_name": "APITest2",
use `APITest` for all instead of `APITest2`, `APITest3`, seems more professional that way.

2022-02-25 07:34 UTC, joeyhorst commented
@naincygoyal what is important and needs to be done in the short run is informing the user that they need to create an account in portal.gresb.com and use api.gresb.com for their base URL when making a request.

Soon we will remove the UI from api.grebs.com.

Find all instances like 

https://github.com/GRESB/api-docs/blob/master/source/includes/_oauth2.md?plain=1#L12-L14

2022-02-25 08:45 UTC, naincygoyal commented
@joeyhorst   I have incorporated the review comments , please have a look into it once and let me know if any modification require.
https://github.com/GRESB/api-docs/commit/58a2577f1915f1870d08bf29c1a273994b37d276

2022-02-25 12:21 UTC, joeyhorst commented
@naincygoyal you will have to resolve my comments and then push your new commits to this PR in order for me to do a second review.

2022-02-28 15:40 UTC, joeyhorst requested changes
one breaking comment, the other a suggestion.

2022-02-28 15:40 UTC, joeyhorst commented on source/includes/_assets.md
> +  - asset size
`asset_size` is part of the annual data, not the building characteristics, although the UI shows it as such.

```
    "annual_data": [
        {
            "year": 2020,
            "asset_name": "The White House",
            "whole_building": true,
            "asset_size": 500
```

2022-02-28 15:40 UTC, joeyhorst commented on source/includes/_assets.md
> +    "annual_data": [
did you make the example(s) shorter?

2022-03-03 15:47 UTC, naincygoyal commented
@joeyhorst  These are the new changes which I made please review it once and let me know if any further changes are required.

https://github.com/GRESB/api-docs/pull/89/commits/bce535509b90a0b2b6f52bdb68ee943b6cd5f25e

2022-03-04 10:53 UTC, joeyhorst commented
@naincygoyal https://github.com/GRESB/api-docs/commit/bce535509b90a0b2b6f52bdb68ee943b6cd5f25e#r67953623

2022-03-07 09:36 UTC, joeyhorst approved these changes

2022-03-07 10:10 UTC, merged